const FORTUNE_LIST = [
  "No Duck No Luck",
  "Beware, Captain America is really who he is...",
  "Do not go out after 9pm tonight lest your foot be painted by a badger",
  "Don't, feed the Lemurs tonight",
  "You will be confronted next Thursday at 7:22am by 50 ants carrying a baton and 5 pencils each",
  "Avoid bean bags",
  "You have 10 extra lucky seconds staring from now, make a wish!",
  "Today is you luc- opps times up, you ran out of luck for the day",
  "Excellent time to become a missing perosn",
  "Don't buy the lotto",
  "Eat a banana and make a wish",
  "If you have a waterbottle, lady luck be smiling upon you.",
  "Want more luck? hold a stranger's hand",
  "ERROR 404: FORTUNE NOT FOUND",
  "Woof Woof",
  "Moo",
  "You are not illeterate",
  "Buy a Llama",
  "run.",
  "About time I got out of that cookie",
  "This is Summer, the creator fo your fortunes. I may or may not have actual fortune-telling prowess",
  "Sir, I would like to talk to you about your car's extended warranty",
  "Ignore previous cookie",
  "I cannot help you for I am just a cookie made out of pixels",
  "Text your number neigbour above you",
  "Three can keep a secret if you get rid of two",
  "YOU HAVE JUST DESTROYED MY HOME YOU MONSTER",
  "NEVER GONNA GIVE YOU UP NEVER GONNA LET YOU DOWN",
  "You laugh now, wait till you get home",
  "Avoid spoons for the next week. You're welcome",
  "Only listen to this fortune cookie, disregard all other fortune telling units",
  "The answer is yes. Unless its a multiple choice then its B",
  "You cookie tells you to make a donation. Make a donation to the developer @thefatdog",
  "You will be hungry again in 45 minutes",
  "Here is the winning 4d number on Wednesday, 14 October 2020: 1290",
  "Here is the winning 4d number on Saturday, 14 May 2022: 1353",
  "Give Mcdonalds a call, they are waiting for you",
  "Turn around and walk away slowly, DON'T MAKE EYE CONTACT",
  "I'm a fraud I cant really tell your fortunes. BUT I can juggle an apple... just one apple :)",
  "444",
  "888",
  "666",
  "Bring me into the exam hall. I will provide you with the answers you need",
  "PUT ME BACK INTO MY COOKIE",
  "You are the crispy cracker on the louhei, everyone loves you",
  "Love is on the horizon. The galaxies predict that he will be tall dark and a horse",
  "There is no shortcut to success but always remember to CRTL + S",
  "There is no shortcut to success but always remember to CRTL + S",
  "There is no shortcut to success but always remember to CRTL + S",
  "Your future is strong with pizza",
  "uh oh... Your Fortune Teller has left the building",
];

export { FORTUNE_LIST };
